### ISSUE TITLE
Add Package Error message

### ISSUE THREAD

**Issue by williamkung** [adamrushy/OpenAISwift#10]
hi,
Add Package
Xcode 13, ios 15

Error message:

Dependencies could not be resolved because 'OpenAISwift' contains incompatible tools version (5.7.0) and root depends on 'OpenAISwift' 1.0.0..<2.0.0.

**Comment by adamrushy** [comment]
Thanks, @williamkung I shall investigate further

**Comment by adamrushy** [comment]
PR is now raised for this one @williamkung
