### ISSUE TITLE
sendChat model .gpt4(.gpt4)  throws Error

### ISSUE THREAD

**Issue by ktorimaru** [adamrushy/OpenAISwift#103]
sendChat model .gpt4(.gpt4)  throw Error:
▿ OpenAIError
  ▿ chatError : 1 element
    ▿ error : Payload
      - message : "The model: `gpt-4` does not exist"
      - type : "invalid_request_error"
      - param : nil
      ▿ code : Optional<String>
        - some : "model_not_found"

model: .chat(.chatgpt) works fine.

**Comment by MarkHoath** [comment]
What release are you running ?

**Comment by ktorimaru** [comment]
1.4.0

**Comment by MarkHoath** [comment]
Do you have access to the gpt-4 api ? I have no problems using sendChat with gpt-4

**Comment by ktorimaru** [comment]
API Access

On July 6, 2023 , we gave access to the [GPT-4 API](https://platform.openai.com/docs/models/gpt-4) (8k) to all API users who have made a successful payment of $1 or more. We plan to open up access to new developers by the end of July 2023, and then start raising rate-limits after that depending on compute availability.

My total spending is under a dollar, that must be the problem

I'm getting close, I will let you know.

**Comment by ktorimaru** [comment]
So, I got my spending over $1 and have waited several days with no change.
Would you consider trying out my project to see if it will run for you?
https://github.com/ktorimaru/AITool.git

**Comment by MarkHoath** [comment]
I downloaded your project, but you appear to be saving and loading the apiKey in each document. 
I cant find in the interface where to upload my apikey.
I suggest you create a global and use the same key for each document. (saving the key with document cant be secure).
I also couldn't see how to run the scripts, or make changes to them.
If your project is working with chatgpt, I would finish off the interface and see if you eventually get gpt4 access.

**Comment by ktorimaru** [comment]
Mark,

Clearly I need to work on the interface! The “Gear” button brings up the API key dialog. It is suppose to come down automatically if you don’t have one setup. Clicking on “New” creates a new script. Once you have a script, click “Iterate” to run the script.

Thanks,

Ken

**Comment by MarkHoath** [comment]
Actually your Gear and Iterate buttons are only on a Mac Build and I was using iOS.
In any event. My API Key works for both chatgpt and gpt4, so you just need to wait to be added to the gpt4 list.
I got an email once I was accepted....  Good Luck :)

**Comment by ktorimaru** [comment]
Thanks! 
Sorry, I had forgot the iOS part was still there.

Do you see any value in the project?

Ken

**Comment by MarkHoath** [comment]
This should be closed. Its not a bug/issue

**Comment by ktorimaru** [comment]
Thanks
