### ISSUE TITLE
theres a typo for URLRequest it say inout instead of "input"

### ISSUE THREAD

**Issue by Alexx1105** [adamrushy/OpenAISwift#121]
let baseURL: String
        let endpointProvider: OpenAIEndpointProvider
        let session:URLSession
        let authorizeRequest: (inout URLRequest) -> Void

**Comment by marcoboerner** [comment]
@Alexx1105 it's not a bug, `inout` is a Swift language feature. See here for example [https://www.hackingwithswift.com/sixty/5/10/inout-parameters](https://www.hackingwithswift.com/sixty/5/10/inout-parameters)
