### ISSUE TITLE
Gpt's answers is not relevant to the question

### ISSUE THREAD

**Issue by tranhuudang** [adamrushy/OpenAISwift#17]
I don't know if this happen to others, but mine is completely weird. Everything working fine yesterday but now even a "hi" message from me will get an article about world war or something really random.

**Comment by Ravipo** [comment]
Send your code, maybe some can help you

**Comment by akardas16** [comment]
that is true please see question and answer below
input: Hi there
response: [TalkAI.Choice(text: "!\n\nMy name is Vishnu and I\'m a Senior Technical Support Manager at an IT-Services company. I\'m responsible for providing technical support and guidance to my team, as well as escalating and resolving customer issues. I have over 10 years of experience in this position, and I\'m adept at troubleshooting complicated technical issues and helping customers get their products and services back up and running quickly.\n\nMy technical expertise includes software installation, hardware troubleshooting, network configuration, cloud hosting, and more. I\'m also experienced in customer service and can provide helpful guidance to my team, especially when dealing with difficult customers. I\'m passionate about helping customers and building relationships with them to ensure satisfaction and loyalty.\n\nIf you have any questions about")]

**Comment by akardas16** [comment]
Hi I found that when you say Hi there, the AI try to complete with rest of text. like in my example (Hi there, My name is ...). the solution is put ? at the end of your question.

**Comment by Yoddikko** [comment]
This is true, it's giving me the same random asnwers even to normal questions.

**Comment by akardas16** [comment]
> This is true, it's giving me the same random asnwers even to normal questions.

put question mark (?) at the end of your questions.

**Comment by Yoddikko** [comment]
Every single answer is random, am I the only one? ![image](https://user-images.githubusercontent.com/92546954/213432410-09cabf89-2c26-49f6-b352-e4caa4abbd2a.png)

**Comment by Yoddikko** [comment]
Fixed it, if you ever get random answers, check what input are you sending. For error I was sending an empty string.
