### ISSUE TITLE
Critical Bug Anyone can see Secret API KEY

### ISSUE THREAD

**Issue by aryan1107** [adamrushy/OpenAISwift#26]
<img width="713" alt="Screenshot 2023-02-06 at 1 23 48 AM" src="https://user-images.githubusercontent.com/31214277/216898874-b598d529-627a-4931-9d8b-08a889b6c357.png">

**Comment by adamrushy** [comment]
Yes and OpenAI advises the following:

> Remember that your API key is a secret! Do not share it with others or expose it in any client-side code (browsers, apps). Production requests must be routed through your own backend server where your API key can be securely loaded from an environment variable or key management service.
