### ISSUE TITLE
Not actually ChatGPT. Is it only with me?

### ISSUE THREAD

**Issue by Refluent1** [adamrushy/OpenAISwift#27]
I finished developing my application with this package when I started asking the AI questions. I quickly realised, the AI did not remember past texts like the real ChatGPT, but I thought it was just a bug, so I continued asking.

I then asked it what it's name was, where it responded with Susan. Again, I thought it was just a bug so I continued asking. Finally, I asked it this:

Me: What company were you developed by?
AI: I was developed by Amazon Web Services (AWS) as part of their suite of cloud-based services.

I just wanted to make sure if this was true for others. If not, then I guess it has something to do with me.

**Comment by MarkHoath** [comment]
OpenAI does not keep a history like Chat GPT does... If you want to send a history, keep a record of the past requests and responses and send them with a new request.

**Comment by marcusziade** [comment]
No library uses ChatGPT currently. The API isn't public. The about text of this repo is lying to you to get easy GitHub stars.

**Comment by adamrushy** [comment]
As @MarkHoath mentioned ChatGPT contains added functionality on top of the OpenAI API - this library is simply a facade to this API to make it easier to create something like ChatGPT or anything else you might think of. Closing the issue on that basis - thank you!
