### ISSUE TITLE
questions & answers not in a closed chat

### ISSUE THREAD

**Issue by Pythonaire** [adamrushy/OpenAISwift#30]
Using a web browser, the conversation is "hold" in a single chat. In that case, answers can be related to older questions inside the "closed chat".  Is where a chance to reach the same by using OpenAISwift?

**Comment by adamrushy** [comment]
@Pythonaire it's not really the intention of the library. Feel free though to build the persistent store inside the app to do the same. Going to close but thanks for the suggestion and good luck :]
