### ISSUE TITLE
Unable to pass in temperature 

### ISSUE THREAD

**Issue by chadham** [adamrushy/OpenAISwift#31]
The OpenAI Api allows you to optionally pass a temperature number value (defaults to 1) letting the model knowwhat sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

The current version of OpenAISwift doesn't seem to allow this. 

Can this be added as a pass through value? Similarly there are other values besides temperature that could be passed in optionally.

**Comment by turangarusso** [comment]
Chadham check my [Pull request](https://github.com/adamrushy/OpenAISwift/pull/32).

**Comment by adamrushy** [comment]
Thank you, merged ✅
