### ISSUE TITLE
Update to latest model 3.5

### ISSUE THREAD

**Issue by nathjyo** [adamrushy/OpenAISwift#34]
Its not really an issue, 

I should of done a pull request but figured it would get seen faster here, 

was wandering about an update to support GPT 3.5 specifically gpt-3.5-turbo

its much quicker and cheaper and has training data up to sep 2021

I was going to update my own packages but would lose it when I update next

cheers

**Comment by underthestars-zhy** [comment]
Yes, we should upload this package to the latest api

**Comment by adamrushy** [comment]
PR is open and will merge today! Thank you for reporting 👍🏼
