### ISSUE TITLE
not aware of the previous conversations

### ISSUE THREAD

**Issue by moonknightskye** [adamrushy/OpenAISwift#38]
first of all im very impressed how easy this library to use! I have implemented this to my app in less than an hour! thank you so much for spending hundreds of hours to make this awesome!

i am new to this section and please delete if this is not the place to ask this but i am curious why the chats are not "remembered". if i ask a question then follow it with another question after, it never remembers even my previous message. is this feature will be supported here? or this is something not a concern at all?

**Comment by bogdanf** [comment]
The short answer is: You have to use the new 'chat' endpoint and provide the history of the conversation with each and every new request.

**Comment by adamrushy** [comment]
Yes, exactly what @bogdanf said.

We don't provide any persistence layer within the framework and would be required from your client integration to handle this. Thank you!
