### ISSUE TITLE
How to convert the response into a string 

### ISSUE THREAD

**Issue by max21910** [adamrushy/OpenAISwift#6]
I have this :
success(OpenAISwift.OpenAI(object: "text_completion", model: "text-davinci-003", choices: [OpenAISwift.Choice(text: "\n\nHi there! Nice to meet you.")]))
how to convert this into a string to have a text with the response in my main view ?

**Comment by adamrushy** [comment]
Hello!

You just need to access the text parameter returned in the response, something like this:

```
openAPI.sendCompletion(with: "A random emoji") { result in
    switch result {
    case .success(let object):
        print(object.choices.first.text)
    case .failure(let error):
        print(error)
    }
}
```
