### ISSUE TITLE
change object property to be optional?

### ISSUE THREAD

**Issue by a-elnajjar** [adamrushy/OpenAISwift#62]
I have this error when my client iOS App requests from the OpenAI endpoint 

▿ Result<OpenAI<TextResult>, OpenAIError>
```
  ▿ failure : OpenAIError
    ▿ decodingError : 1 element
      ▿ error : DecodingError
        ▿ keyNotFound : 2 elements
          - .0 : CodingKeys(stringValue: "object", intValue: nil)
          ▿ .1 : Context
            - codingPath : 0 elements
            - debugDescription : "No value associated with key CodingKeys(stringValue: \"object\", intValue: nil) (\"object\")."
            - underlyingError : nil
```
I check the source code of struct OpenAI. can we make change the object to optional?
the struct openAI should be like 
```
public struct OpenAI<T: Payload>: Codable {
    public let object: String?
    public let model: String?
    public let choices: [T]
} 
```

**Comment by adamrushy** [comment]
Yeah it's incoming 👍🏼

**Comment by a-elnajjar** [comment]
thank you

**Comment by GengJian** [comment]
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/13254245/228455206-9f34a031-5b5b-4371-9323-64a9d3d4d345.png">
same problem T.T

**Comment by adamrushy** [comment]
New release created which includes this change 👍🏼
