### ISSUE TITLE
reade the API key from plist file or iOS Target Properties

### ISSUE THREAD

**Issue by a-elnajjar** [adamrushy/OpenAISwift#64]
Can we add a feature to read the API key from Info.plist  file in UIkit or iOS Target Properties switUI?

**Comment by workingDog** [comment]
I think this is not such a great idea. The API key should be stored in keychain, not in plain text in a file.

**Comment by bogdanf** [comment]
Please don't store the API key in such an obvious way. But if you must, it's easy to implement the "feature" in your own code and just "feed" the API key string to the OpenAISwift.

**Comment by adamrushy** [comment]
Yeah, this is a client level decision! Closing issue 👍🏼
