### ISSUE TITLE
Update Release Version

### ISSUE THREAD

**Issue by MarkHoath** [adamrushy/OpenAISwift#88]
The latest release 1.3.0 (Zip File / Main etc) does not include the GPT4 support in the OpenAIModelType file.

Could this please be included and can the "Release" function be implemented in GitHub so we can download with Package Manager the latest release.

**Comment by dogyungkim** [comment]
Yes Please~~

**Comment by ktorimaru** [comment]
Please

**Comment by adamrushy** [comment]
Sorry for the delay, 1.4.0 is now released ✅
